version: '3'
services:
  rest:
    container_name: johnd_dev_note_taking
    image: johnd_dev_note_taking:1
    build: .
    env_file:
      - ./note_taking_fast_api/.env
    command: sh -c "bash start_server.sh"
    networks:
      johnd_dev_personal_data_center:
        ipv4_address: 20.20.20.100
    volumes:
      - ./note_taking_fast_api:/note_taking_fast_api

networks:
  johnd_dev_personal_data_center:
    external: True